### ISSUE TITLE
Mesh::PrepareGeometricData is sensitive to order of elements in GeomParam table

### ISSUE THREAD

**Issue by a-a-danilov** [INM-RAS/INMOST#3]
Mesh::PrepareGeometricData() updates geometric data in the same order the table was filled by user.
If the user mixed up the default order, for example:
```
                Mesh::GeomParam table;
                table[MEASURE] = CELL | FACE;
                table[CENTROID] = CELL | FACE;
                table[BARYCENTER] = CELL | FACE;
                table[NORMAL] = FACE;
                table[ORIENTATION] = FACE;
                m->PrepareGeometricData(table);
```
then the orientation of the faces will be fixed in the end of PrepareGeometricData(), and thus cell volumes may be computed incorrectly.

It is not clear, if this is a bug, or a feature. It should be either fixed, either documented as intended behavior.

**Comment by kirill-terekhov** [comment]
Certanly a bug, not a feature.
