### ISSUE TITLE
Mesh::Load() and pvtk files with big number of pieces

### ISSUE THREAD

**Issue by a-a-danilov** [INM-RAS/INMOST#5]
Consider the following case: pvtk mesh with M pieces is loaded using Mesh::Load() on N processes.
If M >> N several pieces are loaded on the same process. It may appear that these pieces share some nodes, edges and faces. It looks like in some cases it brokes the whole mesh.

Specific examples:
Generate two meshes using GridGen example:
`mpirun -np 4 ./GridGen 4 32 32 32     →  grid-4.pvtk`
`mpirun -np 8 ./GridGen 4 32 32 32     →  grid-8.pvtk`

Then compile the simple example.cpp with following lines:
```
m->Load(argv[1]);
m->Save("dump.pvtk");
```
and try
`mpirun -np 2 ./example grid-4.pvtk`
`mpirun -np 4 ./example grid-8.pvtk`
in both cases dump.pvtk will be corrupted

**Comment by kirill-terekhov** [comment]
By the way, instruction of generating meshes by GridGen and renaming them is prone to error. grid-4.pvtk depends on grid[0-3].vtk and those are rewritten by subsequent call.
